import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from fpdf import FPDF
from datetime import datetime
from loguru import logger
from config.settings import settings

class AdvancedPDFReport(FPDF):
    def header(self):
        self.set_font('Arial', 'B', 15)
        self.set_text_color(40, 40, 40)
        self.cell(0, 10, f'ChainSentinel Enterprise - Quantitative Audit', 0, 1, 'C')
        self.line(10, 20, 200, 20)
        self.ln(10)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, f'Generated by AI Risk Engine | Page {self.page_no()}', 0, 0, 'C')

class ReportGenerator:
    @staticmethod
    def _create_price_chart(prices: list, token_name: str) -> str:
        """Készít egy 30 napos trendgrafikont 7 napos mozgóátlaggal."""
        if not prices: return None
        
        plt.figure(figsize=(8, 4))
        plt.style.use('bmh')
        
        # Nyers árak
        plt.plot(prices, label='Daily Price', color='#2196F3', linewidth=1.5, alpha=0.7)
        
        # 7 napos Mozgóátlag (SMA) kiszámítása
        if len(prices) >= 7:
            sma = np.convolve(prices, np.ones(7)/7, mode='valid')
            # Eltoljuk az SMA-t, hogy a végére illeszkedjen
            plt.plot(range(6, len(prices)), sma, label='7-Day SMA', color='#FF9800', linewidth=2, linestyle='--')

        plt.title(f"{token_name.upper()} - 30 Day Price Trend & Momentum", fontsize=12)
        plt.xlabel("Days (Last 30)")
        plt.ylabel("Price (USD)")
        plt.legend()
        plt.tight_layout()
        
        filename = f"{settings.REPORT_DIR}/temp_trend_{token_name}.png"
        plt.savefig(filename, dpi=150)
        plt.close()
        return filename

    @staticmethod
    def _create_radar_chart(dimensions: dict, token_name: str) -> str:
        """Készít egy 5 dimenziós kockázati radar grafikont."""
        labels = list(dimensions.keys())
        values = list(dimensions.values())
        
        # A radar chartnak be kell záródnia, így az első elemet a végére tesszük
        values += [values[0]]
        angles = np.linspace(0, 2 * np.pi, len(labels), endpoint=False).tolist()
        angles += [angles[0]]

        fig, ax = plt.subplots(figsize=(5, 5), subplot_kw=dict(polar=True))
        ax.fill(angles, values, color='#4CAF50', alpha=0.25)
        ax.plot(angles, values, color='#388E3C', linewidth=2)
        
        ax.set_yticklabels([]) # Rejtjük a belső számokat
        ax.set_xticks(angles[:-1])
        ax.set_xticklabels(labels, fontsize=9)
        plt.title(f"Safety Dimensions (0-10)", size=12, color='black', y=1.1)
        
        filename = f"{settings.REPORT_DIR}/temp_radar_{token_name}.png"
        plt.savefig(filename, dpi=150)
        plt.close()
        return filename

    @staticmethod
    def create_pdf(data: dict, token_name: str, historical_prices: list = None, risk_dimensions: dict = None):
        """Generálja a PDF-et a grafikonokkal beágyazva."""
        try:
            timestamp = datetime.now().strftime("%Y%m%d_%H%M")
            filename = f"AUDIT_{token_name}_{timestamp}.pdf"
            filepath = settings.REPORT_DIR / filename
            
            pdf = AdvancedPDFReport()
            pdf.add_page()
            
            # --- 1. Szekció: Executive Summary ---
            verdict = data.get('verdict', 'UNKNOWN')
            pdf.set_font("Arial", "B", 18)
            pdf.cell(0, 10, f"TARGET: {token_name.upper()}", 0, 1, "C")
            
            # Színezett Verdict
            if verdict == 'Safe': pdf.set_text_color(0, 150, 0)
            elif verdict == 'Scam': pdf.set_text_color(200, 0, 0)
            else: pdf.set_text_color(255, 140, 0)
            
            pdf.cell(0, 10, f"VERDICT: {verdict} (Risk Score: {data.get('score', 0)}/100)", 0, 1, "C")
            pdf.set_text_color(0, 0, 0)
            pdf.ln(5)

            # Szöveges AI összefoglaló
            pdf.set_font("Arial", "B", 12)
            pdf.cell(0, 8, "AI Executive Summary:", 0, 1)
            pdf.set_font("Arial", "", 11)
            safe_summary = str(data.get('summary', '')).encode('latin-1', 'replace').decode('latin-1')
            pdf.multi_cell(0, 6, safe_summary)
            pdf.ln(5)

            # --- 2. Szekció: Technikai Grafikonok ---
            trend_img = None
            radar_img = None

            if historical_prices:
                trend_img = ReportGenerator._create_price_chart(historical_prices, token_name)
            if risk_dimensions:
                radar_img = ReportGenerator._create_radar_chart(risk_dimensions, token_name)

            # Ha megvannak a képek, betesszük őket
            if trend_img and os.path.exists(trend_img):
                pdf.add_page() # Új oldal a grafikonoknak
                pdf.set_font("Arial", "B", 14)
                pdf.cell(0, 10, "Quantitative Technical Analysis", 0, 1, "C")
                pdf.image(trend_img, x=15, w=180) # Széles trendvonal
                
                pdf.ln(5)
                pdf.set_font("Arial", "B", 11)
                pdf.cell(0, 6, "Chart Analysis (AI Interpretation):", 0, 1)
                pdf.set_font("Arial", "", 10)
                safe_chart_text = str(data.get('chart_analysis', 'No analysis provided.')).encode('latin-1', 'replace').decode('latin-1')
                pdf.multi_cell(0, 5, safe_chart_text)

            if radar_img and os.path.exists(radar_img):
                pdf.ln(10)
                pdf.set_font("Arial", "B", 14)
                pdf.cell(0, 10, "Risk Radar Profile", 0, 1, "C")
                pdf.image(radar_img, x=55, w=100) # Középre igazított pókháló

            # --- 3. Szekció: Pros & Cons ---
            pdf.add_page()
            pdf.set_font("Arial", "B", 12)
            
            pdf.set_text_color(0, 100, 0)
            pdf.cell(0, 8, "Strengths & Positive Indicators:", 0, 1)
            pdf.set_font("Arial", "", 11)
            pdf.set_text_color(0, 0, 0)
            for p in data.get('pros', []):
                pdf.multi_cell(0, 6, f"+ {str(p).encode('latin-1', 'replace').decode('latin-1')}")
            
            pdf.ln(5)
            pdf.set_font("Arial", "B", 12)
            pdf.set_text_color(200, 0, 0)
            pdf.cell(0, 8, "Risks & Red Flags:", 0, 1)
            pdf.set_font("Arial", "", 11)
            pdf.set_text_color(0, 0, 0)
            for c in data.get('cons', []):
                pdf.multi_cell(0, 6, f"- {str(c).encode('latin-1', 'replace').decode('latin-1')}")

            # Kimentés
            pdf.output(str(filepath))
            logger.info(f"Komplex PDF generálva: {filepath}")
            
            # Takarítás (Töröljük az ideiglenes képfájlokat, hogy ne szemeteljünk)
            if trend_img and os.path.exists(trend_img): os.remove(trend_img)
            if radar_img and os.path.exists(radar_img): os.remove(radar_img)

            return filepath

        except Exception as e:
            logger.exception(f"Kritikus hiba a PDF rajzolásakor: {e}")
            return None

    @staticmethod
    def export_to_excel(data: list, filename: str = "portfolio_export"):
        # Ez marad a régi...
        try:
            filepath = settings.REPORT_DIR / f"{filename}_{datetime.now().strftime('%Y%m%d')}.xlsx"
            pd.DataFrame(data).to_excel(filepath, index=False)
            return filepath
        except Exception:
            return None